### ISSUE TITLE
Server timeout when checking peers_nonoce

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#118]
We recently introduced peers `nonce` check in `Aecore.Peers.Worker.add_peer`. The check was introduced to prevent node from adding itself to list of known peers by making `\info` request to peer that's about to be added and comparing it's nonce to own nonce. This doesn't work as expected, because `\info` requests uses `Aecore.Peers.Worker` so it can't be processed while `:add_peer` call to `Aecore.Peers.Worker` genserver is handled.

Error introduced by 2055e9fb (GH-79)

To reproduce:
```
iex(9)> Aecore.Peers.Worker.add_peer("http://localhost:4000") 
[info] GET /info
[debug] Processing with Aehttpserver.InfoController.info/2
  Parameters: %{}
  Pipelines: [:browser]
:error
iex(10)> [error] GET /info request error
[error] #PID<0.415.0> running Aehttpserver.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /info
** (exit) exited in: GenServer.call(Aecore.Peers.Worker, :get_peers_nonce, 5000)
    ** (EXIT) time out

```

**Comment by cytadela8** [comment]
@HristianHristov take a look

**Comment by d-velev** [comment]
A fix would be to make the nonce for each peer a module attribute in the Peers module and have a getter function for it, instead of having it in the state. I think that will only work if the nonce doesn't change.

**Comment by cytadela8** [comment]
Nonce doesn't change but has to be chosen randomly on start.

**Comment by HristianHristov** [comment]
I will fix it.

**Comment by HristianHristov** [comment]
@cytadela8 Have a look.

**Comment by d-velev** [comment]
Have the peer_nonce attribute in the Peer module and make a normal function that returns it (get_peer_nonce) and have that function called in the info_controller when we want to get the nonce from a peer, that fixes it.

**Comment by HristianHristov** [comment]
@cytadela8 , @d-velev , Think it's done now. How do you think ?

**Comment by cytadela8** [comment]
Looks good. Can you submit PR and I will test and merge later when I'm on computer?

**Comment by cytadela8** [comment]
I just checked and module attributes (`@`) are evaluated compile time. Despite that currently we force users to compile the project for themselves we want to me able to distribute compiled binaries. Having the same nonce on many peers in unacceptable.

**Comment by cytadela8** [comment]
I think the easiest and quite good solution would be to store the nonce in ETS table.

**Comment by gspasov** [comment]
So if I understand you correctly, we need to build the nonce on run time and then save it inside a table. Then, use the nonce written in the table.

Correct?

**Comment by cytadela8** [comment]
@gspasov Yes, we should choose a random nonce on start and have a function that allows to access it. Using ETS table enables us to access the nonce while `Aecore.Peers.Worker` is blocked by some operation (the problem mentioned in issue description).
