### ISSUE TITLE
Changes for local multinode

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#119]
We should make it possible to launch multiple local nodes without conflicts by changing environment variables. To do that we have to make it possible to change following configs with environment variables:
- [x] persistence table path
- [x] node port

**Comment by thepiwo** [comment]
Yes we could make the port phoenix listens on, configurable via environment variable

**Comment by thepiwo** [comment]
@meivantodorov can you check why the persistance breaks when starting multiple nodes? I tried with `PORT=4001 iex -S mix phx.server` and `PORT=4002 iex -S mix phx.server` in a different terminal
