### ISSUE TITLE
Multinode environment 

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#127]
We should create script(s) (a Makefile maybe?) so one would be able to easily launch multiple nodes locally for testing purposes.

This depends on #119

**Comment by nedelcho-delchev-tues** [comment]
So the script(s) should work something like this: 
- Start N nodes with one node that is always starting, lets say master node running on port 4000
- After each node is started - connect it to the master node
- The master node should start mining

Any ideas and suggestions are welcome, there is a prototype script in #127 branch

**Comment by cytadela8** [comment]
I would suggest also following functionalities:
- allow to disable auto connecting to master (and mining on master)
- provide easy way to start and stop the nodes separately
- take care of persistence database = `PERSISTANCE_PATH` (have them separated and add some command to clean all of them)
- easy way to connect to the iex shells of nodes
