### ISSUE TITLE
replace key worker with elixir-wallet

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#132]
can be started when https://github.com/aeternity/elixir-wallet/issues/58 is finished

**Comment by thepiwo** [comment]
I guess @gspasov would be ideal to do this task

**Comment by gspasov** [comment]
@thepiwo Should I add the elixir-wallet as a separate app, or just change the functionality of the Keys module?

**Comment by thepiwo** [comment]
The elixir wallet should be included as hex dependency and the Key Manager should be removed. Wherever the Key Manager is called functions from the wallet should be called now

**Comment by gspasov** [comment]
Looking at the Keys module, it seems that I won't be able just to remove it and use the functionality from the elixir-wallet, because in this module there are some things that I cannot do simply with the elixir-wallet functions. Maybe I can alter the module to such extend that I use the functions from the elixir-wallet, but leave the other stuff.

**Comment by thepiwo** [comment]
signing should work with the wallet as well, what other issues are there?

**Comment by gspasov** [comment]
There is a signing functionality in the wallet, but the signing function in the core is different in the way that it actually creates the Tx itself:
```elixir
def sign_tx(to_acc, value, nonce, fee, lock_time_block \\ 0) do
    {:ok, from_acc} = pubkey()
    {:ok, tx_data} = TxData.create(from_acc, to_acc, value, nonce, fee, lock_time_block)
    {:ok, signature} = sign(tx_data)
    signed_tx = %SignedTx{data: tx_data, signature: signature}
    {:ok, signed_tx}
  end
```

**Comment by thepiwo** [comment]
yeah you can put this function in the SignedTx and call the wallet code from there

**Comment by gspasov** [comment]
Blockers: [This](https://github.com/aeternity/elixir-wallet/pull/78) pull request should be accepted before we continue our work. I have fixed the namings of the modules.
