### ISSUE TITLE
implement nakamoto consensus, follow the latest valid chain

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#133]
- [x] follow the longest valid chain
- [x] if there are 2 valid blocks at the same height, wait for the following block
- [x] if there is a chain discovered that can get validated, replace the current one with it

can be started after #97

**Comment by cytadela8** [comment]
>  if there are 2 valid blocks at the same height, wait for the following block
Shouldn't we maybe compare them by hash? (lower is better?) We have to choose something if we would like to mine.

**Comment by thepiwo** [comment]
no, this would be a "most work" kind of consensus, as the miner we choose the one we received earlier to maximize possible profit. We will research other consensus mechanisms in the future, if you have any ideas we can discuss them and build a prototype to validate.

**Comment by cytadela8** [comment]
ok, I understand now.

**Comment by thepiwo** [comment]
closed by #162
