### ISSUE TITLE
api functions protected by key, to control node

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#134]
- [ ] add http api functions to control the node, e.g. start/stop miner
- [ ] protect the api using `authorization` header to match a key from config or environment

**Comment by cytadela8** [comment]
When we are at: we should store a SHA hash of the key instead of the key (for better security).

**Comment by cytadela8** [comment]
If the private API should also have a separate server so it can be only accessible from localhost.

**Comment by thepiwo** [comment]
no, we want it to be accessible from remote as well, if the node provider wants to control a node running on a server. I think authorization token header is sufficient for security
