### ISSUE TITLE
Dialyzer

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#160]
- [ ] add `@spec` to functions missing it
- [ ] fix dialyzer errors
- [ ] ~~add dialyzer to Travis~~ dialyzer for elixir is not ready to be used as part of CI.
- [x] add dialyzer to mix

**Comment by untra** [comment]
>  add dialyzer to Travis

I would actually advice against this at the moment; unfortunately dialyzer and elixir are not fully copacetic, and there are a lot of reported false positives (`The created fun has no local return`). Dializer is also currently convinced certain functions consuming `SignedTx.t()` should instead have success typings consuming `atom()` instead.

Dialyzer is still a good tool to identify serious mistakes, and even more mistakes are prevented when public methods get `@spec`'d. But I think there is more work involved before Dialyzer is ready to run as part of CI. :confused:

**Comment by cytadela8** [comment]
@untra Ok, I removed that from checklist.
