### ISSUE TITLE
Dev environment releases not working 

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [aeternity/elixir-research#171]
The dev releases are not working right now due to major changes. You can use **multi_node_screen.sh** for now

I will wait for all the major PRs to be merged before fixing it.

**Comment by untra** [comment]
I was also having trouble getting the the dev build to work over the weekend. My problems were around rustler and compiling rox, however. Is that currently the issue?

The `multi_node_screen.sh` worked to make an effective release, but I wasn't sure how to use it further after staring up the release with the `console` command.

**Comment by nedelcho-delchev-tues** [comment]
Yes, the issue is about rox not compiling and the application can't start properly I suppose. I will fix it in the coming days.
