### ISSUE TITLE
Parser, lexer and interpreter for smart contract language

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [aeternity/elixir-research#178]
Implementing prototype parser and lexer for a smart contract language

WIP: Implementing an elixir interpreter for the language.

## Example:

```
Contract contract_name(account:Hex){

  func sum(first:Int, second:Int){
    first+second;
  }

  a:Int = 5;
  b:Int = account_balance(account);

 foo(a, b);

}(0x04711AC9E3D5EA12D948A41F8661C498CC5DF93B85C1E91172E571B312EB56AAD2046845456FA416F3DF5D04954AD6E6C6A8FF13A11DA574542B56F58DEFF052E4);
```
Example might change in the course of development, so can the syntax

### Interpreter: 15.03.2018

https://github.com/aeternity/elixir-research/blob/GH-178/apps/aernold/README.md

**Comment by thepiwo** [comment]
@cheezus1 @nedelcho-delchev-tues would you give yourselves a new timeframe to have this finished?

**Comment by thepiwo** [comment]
we will abandon this issue for now, to try focusing at getting the implementation closer to core-team specifications
