### ISSUE TITLE
Dimitar - Payment channels prototype

### ISSUE THREAD

**Issue by d-velev** [aeternity/elixir-research#185]
### What I want to achieve: 
A broadcasts a channel invitation transaction (non-mineable) with B stated as the second party. Whenever this transaction reaches B's pool, he is notified that A wants to open a channel with him. B can then accept A's invitation which sends a half-signed transaction back to the person inviting. He then creates the channel opening transaction and adds it to the pool, this transaction also includes the funds both accounts want to lock to the channel. These funds are deducted from their on-chain state. From then on, both parties can propose payments to one another, and if they are accepted, a transaction which could settle the outcome of their business is created with an index that is increased after each transaction. The transaction that closes the channel is the one with the highest index. It will also specify the amount to be added to the two accounts. The transactions concerning channel opening will also include the accounts' respective uri. The invitation transactions will possibly have a TTL. If the invitation is accepted or the TTL is exceeded, the transaction will be removed from the pool. The fee for the channel opening will be paid by the one accepting the invitation, half of the fee will be automatically transferred from the funds of the one inviting. Channels can be closed at any moment by either of both parties.

### What I did:
As @cytadela8 and @thepiwo suggested, I left the communication to be done by the two nodes, this makes it so that there's no gossip in the network, but requires the nodes to be online if they want to be able to connect to each other, their URI is also only exposed to the node they are doing business with. I've also filtered out the newly added transaction types from any chainstate operations, these types are:
-MultisigTx - contains data and a map of signatures with the public key as key.
-ChannelTxData - contains the amount to be locked/ added to the public key's balance and a fee to be paid for the transaction. Channels are opened and closed with this transaction, a way to differentiate opening and closing would be to set a different sign for the values (either subtract or add the amount to the balance).

A node can send a channel invitation by specifying the URI, the amount he wants to lock to this channel and a fee to be paid for the opening (the fee is split between the two accounts when the transactions are validated, the same can be done for chainstate operations). The node that has received an invitation can see it by calling Peers.Worker.pending_channel_invites(). To accept the invite, the node has to reference the address of the node inviting and specify the funds he wants to lock as well. Whenever the invitation is accepted, a transaction is added to the pool. When this transaction is mined, the peers check if they have pending invitations with each other. If they do, they open a channel (the data for open channels is stored in the Peers state). From then on, they can make payments to channels they have open by referencing the address of the node and the amount they want to pay. The one receiving the payment can check for pending transactions and accept them. When accepted, a new transaction is added to the list of channel transactions with the updated amounts. Channels can be closed at any time without agreement from the other node, this is achieved by adding the opening transaction to the list of channel transactions from the start, making it the first valid transaction that can close the channel. The Scheduler module checks if our currently open channels are present in the corresponding node's state as well, if not - they are removed from our state as well.

### Channel related functions:

> Channels.invite(peer_uri, amount, fee)
> Channels.accept_invite(peer_pubkey, amount)
> Channels.make_channel_payment(address, amount)
> Channels.accept_pending_tx(address)
> Channels.close_channel(address)
> Peers.pending_channel_invites()
> Peers.pending_tx(address)
> Peers.open_channels()

### An example run:

> node1: 
> iex -S mix phx.server
> 
> node2: 
> PORT=4001 PERSISTENCE_PATH=apps/aecore/priv/rox_db_4001 iex -S mix phx.server
> 
> node1: 
> alias Aecore.Keys.Worker, as: Keys
> alias Aecore.ChannelsPrototype.Channels
> alias Aecore.Peers.Worker, as: Peers
> 
> node2: 
> alias Aecore.ChannelsPrototype.Channels
> alias Aecore.Peers.Worker, as: Peers
> alias Aecore.Miner.Worker, as: Miner
> 
> node1:
> #set a different pubkey for node1
> Keys.delete
> Keys.new("abc")
> Channels.invite("localhost:4001", 30, 10)
> 
> node2:
> node1_address = Peers.pending_channel_invites |> Map.keys |> Enum.at(0)
> Channels.accept_invite(node1_address, 20)
> Miner.resume
> #wait a few seconds before suspending
> Miner.suspend
> Channels.make_channel_payment(node1_address, 15)
> 
> node1:
> node2_address = Peers.open_channels |> Map.keys |> Enum.at(0)
> Channels.accept_pending_tx(node2_address)
>

**Comment by cytadela8** [comment]
> A broadcasts a channel invitation transaction (non-mineable) with B stated as the second party. Whenever this transaction reaches B's pool, he is notified that A wants to open a channel with him. B can then accept A's invitation which sends a half-signed transaction back to the person inviting. He then creates the channel opening transaction and adds it to the pool

I would leave the whole exchange process to the user. (to applications using our blockchain)

**Comment by vans163** [comment]
Can a state channel be opened to a smart contract?  This is so an action can be done in response to sending a micropayment?

**Comment by thepiwo** [comment]
@vans163 it is an interesting idea and should be possible in general.
This protoype won't support this, as there are no smart contracts yet.

for our state channel specification you can have a look at https://github.com/aeternity/protocol/blob/channels/CHANNELS.md and leave comments and questions

**Comment by thepiwo** [comment]
will close, for now, maybe we can revisit when implementing state channels
