### ISSUE TITLE
Prototype - Proof of Stake Voting

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#190]
# Basis Proof of Stake Voting

## Idea

Let accounts, make on-chain transactions representing votes to a given question. The mechanism for counting votes should be the amount of tokens held by the account determining the weight of the vote.

## Implementation Proposal

**Question Transaction**
Any account can create a transaction, asking a question to hold the vote over. It should specify an question as plain text, as well as an `close_block_height` at which the voting on this is closed. Otherwise the transaction should include the normal fee, nonce and from_account fields and signature. These questions can either be boolean, yes - no questions or the transaction could include an array of possible answers.

These questions can be indexed in the `chain_state` for easy referencing and providing apis.

**Vote Transaction**
Any account can vote on previously opened questions using a vote transaction. This should include the hash of the question transaction, as well as the answer, either boolean or referencing one of the possible answers. Otherwise the transaction should include the normal fee, nonce and from_account fields and signature.

These answers can be indexed in the `chain_state` for easy referencing and providing apis.

**Closing Vote (Proposal 1)**
The account that created the question transaction, creates an close vote transaction after the `close_block_height` of the transaction, publishing the results of the question. In counting the results he consideres vote transactions by weight of tokens held in the block of `close_block_height`.

**Closing Vote (Proposal 2)**
It is each clients task to count the results by the chain_state in the block of `close_block_height`.

## Advanced Topics

- delegating voting power (but not tokens) to other accounts, for all/specific votes or timeframe

**Comment by meivantodorov** [comment]
### What we did:

Created 3 new transaction data structures: **VotingQuestionTransaction**, **VotingAswerTransaction** and **VotingTansaction**. 

### VotingQuestionTransaction
We are registering new question in chainstate by his hash. 

### VotingAnswerTransaction
We are registering new answer for a question by providing his hash

### VotingTransaction
It is a wrapper for the VotingAnswerTransaction and VotingQuestionTransaction. We are makeing
SignedTx from VotingTransaction

@Artur64 will finish the documentation

**Comment by thepiwo** [comment]
What does the `VotingTransaction` wrap, whats the purpose?

**Comment by thepiwo** [comment]
@meivantodorov @Artur64 whats the progress here?

**Comment by thepiwo** [comment]
@DanielaIvanova @Artur64 whats the progress here? you set yourself the deadline on 09.02. could yourself a new one? Maybe the end of the week?

**Comment by DanielaIvanova** [comment]
Ivan told as to fix:
- VotingTx serilizations
- Peer to peer communication with VotingTx
- Merkle tree root problems
- Apply txs to chain
We are working on peer to peer communication with voting txs. We are not sure that we will be ready by the end of the week.

**Comment by thepiwo** [comment]
As this is your (@DanielaIvanova and @Artur64) task, I'd like you to be self-sovereign about finishing it, as Ivan is on holiday now.
What new deadline would you like to give yourselves?

**Comment by DanielaIvanova** [comment]
We will try to finish with Voting Prototype by 28.02.

**Comment by thepiwo** [comment]
good documentation, is this prototype finished?

**Comment by DanielaIvanova** [comment]
We found something that is not working properly and we will try to fix now.

**Comment by thepiwo** [comment]
can you mention `cytadela8` and me, once you are done?

**Comment by DanielaIvanova** [comment]
@thepiwo @cytadela8 
At this moment we are ready with Voting Prototype.

**Comment by thepiwo** [comment]
this prototype is finished (excluding PR #245 comments), but will be abandoned
