### ISSUE TITLE
download blocks in parallel

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#193]
- get a list of block hashes
 - download multiple blocks in parallel (e.g. 10 threads)

**Comment by cytadela8** [comment]
Maybe we should create rather special `/batch_blocks` request? One would pass the hash of "last" block and number of blocks to return.

**Comment by cytadela8** [comment]
I think that's what is implemented in #192

**Comment by thepiwo** [comment]
thats implemented in #192, but here we want to download from different peers in parallel

**Comment by cytadela8** [comment]
Ohh, from different peers. Good idea!
