### ISSUE TITLE
Extendable PoS Voting

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#194]
# Extendable PoS Voting

## Idea

We would like accounts to "vote", the weight of vote should (generally) depend on the balance. There are many different scenarios when that is useful (All kinds of online secure pools, blockchain Governance, DAOs). That's why it's important to find as extendable way of implementing voting. [Below](#solutions) I propose few systems with customisable formulas. The idea behind this prototype is to implement most of the scenarios natively for better performance then an implementation in contracts would achieve.

## Plan

From below set of solutions I'm going to implement OnChainFormula, but with predefined formulas implemented in Elixir. (Instead of specifying Formula code in Question, Question will specify which of implemented by me formulas to use)

- [x] Make it possible to create new types of txs (probably use some of the code from GH-172)
- [x] Add Question transaction that adds Voting related data to chainstate
- [ ] Create interfaces (including web) for pulling data from Votings
- [x] Add Vote transaction
- [x] Add different Formulas

## Possible addictions

- [ ] Find a way to delegate votes. (Probably user could be allowed to set some custom fields in his account state, but how to change formula? Should we move signature validation to formula? Maybe we could store in account-state not only info about balance, but also "voting\_power"?)

## Solutions

Below solutions can be implemented both natively (on blockchain level) or with a contract (if our contract language will allow everything required).

### OnChainFormula

Definitions:
- Voting = a process of supplying a global Answer to Requester after TimeFrame using Votes that affect VotingState according to Formula. Voting is started with Question
- TimeFrame = start block, end block pair. All blocks from block after start block to end block are considered "in"
- Requester = an Account, Contract or the Blockchain
- VotingState = a tuple-like structure representing current state of an ongoing voting.
- Answer = VotingState after TimeFrame end
- Vote = A transaction with tuple-like data that that alters VotingState with Formula. Only one vote per account is allowed. When Voting fee is taken (as normally) from current state of account, but to Formula the state after (at) start block is supplied.
- Formula = A non recursive function in a functional language to be deffined. It has 3 parameters: VotingState, Vote, AccountState. Returns: VotingState. Vote fee has to cover price of Formula calculation.
- Question = A transaction created by Requester specifying TimeFrame, Formula and initial VotingState. The fee has to cover VotingState storage cost.

### OffChainFormula

Above solution (OnChainFormula) allows only for a very limited set of voting algorithms *(for example no median value)*. To allow more complex voting methods we can create an Answer tx and use a special ValidationFormula. This way an algorithm for voting doesn't need to be "easy" to calculate, just validation has to be possible by doing fold\_left on votes with answer supplied.
Changes in comparison to OnChainFormula:
- Question += Has ValidationFormula. Fee has to cover ValidationForumula cost. Formula(s) should be defined in a way to allow only one valid Answer.voting\_result.
- Formula += Has 4th parameter: Answer 
- ValidationFormula = A function in Formula language. Has 2 parameters: Answer and VotingState after all Formula executions. Returns: Boolean = whether Answer.proof is a valid proof of Answer.voting\_result given VotingState.
- Vote += fee has to be >= pesymistic ValidationFormula execution cost
- Deposit = Amount of tokens enough to cover for all Formula fees and ValidationFormula. It is returned to Validator if ValidationFormula returns true.
- Answer = A transaction created by Validator (any account or contract) after TimeFrame. Contains voting\_result and proof tuples. Answer contains Deposit. Has no fee. Only one valid Answer transaction can be made. Execution of Answer if as follows:
    1. Execute Formula on Votes in order with Answer supplied. (beginning VotingState is defined in Question) If at any point deposit will stop covering fees of Formula execution consider Answer invalid and destroy Deposit.
    2. Execute ValidationFormula on VotingState after all Formula executions with Answer supplied.
    3. If ValidationFormula returns true return Deposit to Validator and Answer is valid. Answer.voting\_result is considered a valid result of voting. 

### OffChainFormulaWithQuality

Allow algorithms that can't be validated using previous method, but can me assigned "quality of solution" with previous method.

This can be achieved by adding an "AnswerSupply" time-frame. In it Answer tx-s would be collected, but only after time-frame they would be evaluated starting from the "best one" when a valid tx is found all other are discarded and deposits returned.

### AnyVoting

Allow algorithms that can't be validated in previous ways (for example require going through votes more then ones or in other order). This probably can only be solved by moving voting fully to contracts.

---

*If any of the above is unclear please comment or contact me through Slack. I will edit the description to make my ideas clearer*

**Comment by cytadela8** [comment]
@thepiwo

**Comment by thepiwo** [comment]
@cytadela8 looks really good

**Comment by sennui** [comment]
One way of delegating votes would be to extend an account with field holding address of account which got our votes (votes got delegated to this "recipient" account"). When, the vote runs, voters supply all delegated accounts and voting service validates his claims. Votes given would be equal to current balances of the accounts.

**Comment by cytadela8** [comment]
@sennui 
My concern about delegation was about the cost of: 
1. storing information about delegated accounts supplied by voters. (if it would be part of Vote transaction it would have to be stored on chain). 
2. checking every account that delegated voting power to one voter for every vote. I was considering if such information shouldn't be cached somehow.

A little bit different way of delegating votes that I'm leaning towards is ti handle the delegation in Formula and store delegation info in account "custom fields". The "custom fields" would be just a map that the owner of account would be allowed to change freely to anything with transactions. Formulas could then use those fields to check if an account specified in Vote transaction truly delegated the voting power to voter and could employ any kind of restrictions or weights to such votes or anything.

**Comment by sennui** [comment]
@cytadela8 yes, such formula would let to customize the delegator depending on the vote.

**Comment by cytadela8** [comment]
Rebased and pushed

**Comment by thepiwo** [comment]
Looks really interesting, I have to try some more!

Can you add some examples and documentation here in the issue?

**Comment by cytadela8** [comment]
Hmm, ok. I will try documenting tomorrow. You can try using the unit test as an example guide.

**Comment by thepiwo** [comment]
did you already add some documentation?

**Comment by thepiwo** [comment]
closed as #248 is closed, somewhat finished but will be abandoned
