### ISSUE TITLE
Prototype - Contract signing æpp

### ISSUE THREAD

**Issue by gspasov** [aeternity/elixir-research#197]
# Contract signing æpp using Phoenix

## Usage

This æpp is used only after all the parties signing the contract have agreed on the terms of the contract, so they only need to sign the contract and store it on the blockchain for security purposes.

## Requirements

The two parties, signing the contract, will need to have a wallet, or create one in order to encrypt and decrypt the contract between themselves. The contract will be encrypted at all time, making it impossible for the _client_ or a _"hacker"_ to read its content.

## Process of signing the contract

_**Party A**_ hashes the contract, encrypts the contract with the public key of _**Party B**_ and signs the contract with his own private key. All this is done offline using the [elixir-wallet](https://github.com/aeternity/elixir-wallet) application. All this data will be stored in a file which _**Party A**_ will send to _**Party B**_ using the `Phoenix æpp`.

_**Party B**_ receives the file from the `Phoenix æpp`. Localy using the [elixir-wallet](https://github.com/aeternity/elixir-wallet) application _**Party B**_ will decrypt the contract, verify the signature of _**Party A**_ using his public key. Then the contract will be hashed again and then encrypted using the public key of _**Party A**_. _**Party B**_ will then sign the contract and create a file similar to the one of _**Party A**_ and send it again to the `Phoenix æpp`. The æpp will check the hashes of the contracts and if they are the same then we know the contract is not tampered with from _**Party B**_, and the contract will be send to a node to add it to the blockchain.
 
## Encrypting/Decrypting

In order to be at most secure, the decryption of the contract will be done localy on the PC using the [`elixir-wallet`](https://github.com/aeternity/elixir-wallet) project. Inside the repository a modul will be created for encrypting and decrypting a contract using the parties public and private keys, keeping two copies of the contract, one encrypted for `party 1` and another encrypted for `party 2`.

## Signing of the contract

The signing of the contract will be done locally as well using the [`elixir-wallet`](https://github.com/aeternity/elixir-wallet) repository.

## Plan 

- [x]  Create transaction structure of a signing a contract - `sign_contract_tx` in the core repo with the following structure:
```elixir
[
   title: String.t(),
   pub_key_1: binary(),
   pub_key_2: binary(),
   signature_1: binary(),
   signature_2: binary(),
   encrypted_contract_1: binary(),
   encrypted_contract_2: binary(),
   fee: integer(),
   hash: binary()
]
```
Where `1` and `2` are the parties signing the contract
- [ ] Make an `endpoint` for creating such a transaction in the `elixir-research` project;
- [x] Create a module inside the [`elixir-wallet`](https://github.com/aeternity/elixir-wallet) repository for encrypting and decrypting with public and private keys;
- [ ] Create the Quanterall repo for the Phoenix project;
- [ ] Connect the Phoenix project with a node;
- [ ] Work on the communication between the _Parties_ in the Phoenix project;

## Time-frame: 22.01 - 02.02.2018

For a working prototype

**Comment by cytadela8** [comment]
Sorry for asking such kind of question, but what would be the purpose of publishing such a tx on blockchain? Why store on blockchain some encrypted blobs? Wouldn't it be enough to just publish the hash on blockchain?

I would personally think about following scheme of signing a contract:

1. Parties agree on contract in any way.
2. Parties sign both sign a tx of structure: [hash_of_contract: binary(), parties: list(binary()), max_block: integer()]. (all parts of the structure are signed)
3. The blockchain only accepts the tx if for every party there is valid signature attached and the max_block wasn't reached .

What's missing in my scheme, but should be easy to add is deciding who pays the fee.

By adding the max_block we add to the system a guarantee that if I sign "today" the contract then "tomorrow" I can be sure if the contract was successfully agreed upon or not.

**Comment by gspasov** [comment]
> Why store on blockchain some encrypted blobs?
Because is should be stored what the parties agreed on and it should be in a place where it cannot be tampered (so basically the blockchain), otherwise we would only have a few signatures from the parties that don't mean much in any legal system, because they cannot prove what are the signatures for. The hash of the contract is not enough, because it could not be viewed later on.

**Comment by gspasov** [comment]
The module for `encrypting` and `decrypting` a contract file is done. Issue could be found [here](https://github.com/aeternity/elixir-wallet/issues/89)

**Comment by cytadela8** [comment]
Why the hash is not enough? Both parties can just store the contents of contract that hash to the publicly known and signed hash. Its in the interest of both parties to store the contents of contract and its not in the interest of general public to store some random binary blobs. (Publicly known (and signed by parties) hash makes it impossible without braking the hash function to temper with contract contents.)

**Comment by gspasov** [comment]
In my opinion the idea here is to store the contract on the blockchain as a secure way of keeping it. If it is stored with the parties themselves there is a possibility where they both "lose" the contract. Then nobody could reproduce it, or if even one of the party loses it they'll have to rely on the copy from the other party. When it is on the blockchain they can be sure that it will stay there forever, or at least until the contract ends.

**Comment by cytadela8** [comment]
So I would still disagree on the philosophical level. I wouldn't consider blockchain a place to store significant amounts of data. A contract file will always be at least few kilobytes and can easily reach megabytes if it's (for example) a Word document. Blockchains already struggle with being overloaded with data. (see Bitcoin current per byte prices (not very good example, because of time between blocks and block size limit) and Ethereum gas prices (not very good example, because Ethereum concetrates on price for computation of a transaction))

So that's my opinion.

**Comment by thepiwo** [comment]
I agree with @cytadela8, storing the blob on the blockchain is not the correct way of doing it, hashing would be sufficient.

You can build your prototype like this, but this should not be the way to go.

Maybe you can think of other ways of storing and referencing the blob, like ipfs.

**Comment by gspasov** [comment]
Okay, I see now that I was thinking in the wrong direction. We'll do it how @cytadela8 suggested. We are going to hash the contract before encryption and store it on the blockchain, and the encrypted contracts of the parties can be stored somewhere on the Phoenix server (web app). This way the users will be able to see their previous contracts and the transaction info connected to them (from the blockchain).

**Comment by thepiwo** [comment]
Great, thank you!

**Comment by gspasov** [comment]
After some more in-depth talk about the Contract app we have the following ideas:

**Comment by thepiwo** [comment]
I see a few issues with this

 - what if the `participants` are different in the individual `ContractTx`?
 - will each `ContractTx` hold all previous signatures from other `ContractTx` using the same `contract_hash`? This could lead to conflicts when there are multiple `ContractTx` in the same Block.
 - each `ContractTx` holding all previous signatures and public keys is a lot of overhead.
 - a valid signature could double as `accepted`
-----
I would propose to implement it with two transaction types:
#### ContractProposalTx

used to propose a new contract to be signed by other parties

```
%{
    contract_hash: hash(),
    participants: list_of_accounts(), 
    ttl: block_num()
}
```
#### ContractSignTx

used accept a proposed contract

```
%{
    contract_proposal_tx_hash: hash()
}
```

The indexing of proposed contracts and keeping track of acceptions, could happen in the chain_state or a separate application. 

Yours and mine approach have the downside of needing a special transaction type, making it "hardcoded" in the core blockchain protocol. I think to implement it like this for now, but have a later prototype to build a transaction type for arbitrary data, with minimal validations.

**Comment by gspasov** [comment]
@thepiwo 

This is a good idea, but I have a concern with it. 

Usig this approach means that one of the parties will have to send the ProposalTx and all the other will have to make the SignContractTx. This means that all the other parties will have to wait for this one member to initiate the ProposalTx. Problem lies here, how are the parties going to decide who is going to initiate the Contract, because whoever he is, he'll need to pay a bigger fee, having in mind that the ProposalTx is going to be bigger in size.

In my opinion this approach will work best if it is done Off Chain, let's say in a state chanel, and then only one Tx is going to be send in the Blockchain. But then we would need to wait for the StateChanels to be up and running and stable.

**Comment by thepiwo** [comment]
Either the proposing party is the beneficiary of the contract or he will get paid outside the protocol, any of the parties could initiate a proposal, as long as the fee is payed, which is in any case less than in your initial proposal.

**Comment by thepiwo** [comment]
@HristianHristov whats the progress here?

**Comment by thepiwo** [comment]
@HristianHristov what is the progress here? You set yourself to be finished on 02.02 so can you have a new timeframe set? Maybe end of the week?

**Comment by thepiwo** [comment]
@HristianHristov what is the progress here? You set yourself to be finished on 02.02 so can you have a new timeframe set? Maybe end of the week?

**Comment by HristianHristov** [comment]
I think we could finish with the core by the end of the week, but the separate Phoenix app would require some more time, maybe by the end of the next week.

**Comment by thepiwo** [comment]
will be abandoned

**Comment by thepiwo** [comment]
@HristianHristov we will abandon this task for now, from monday you will work together with @meivantodorov to try getting our project closer to matching core-teams specifications
