### ISSUE TITLE
represent hashes and accounts in json as bech32 with prefixes

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#210]
change hex representation of hashes to bech32 with prefix

this could look like this:
`Bech32.encode("tx", tx_hash_binary |> Aeutil.Bits.extract5)`
using https://github.com/stampery/elixir-bip0173/

`def extract5(str) when is_binary(str), do: for <<x :: 5 <- str >>, do: x`

**Comment by thepiwo** [comment]
wait with this for confirmation if we actually want to use base58check or maybe bech32

**Comment by nedelcho-delchev-tues** [comment]
Why would we want to use bech32, what would we gain from it ?

**Comment by thepiwo** [comment]
It is considered more modern and if we make the effort in changing out serialization, we can just use this.

general motivation: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#motivation

**Comment by thepiwo** [comment]
I updated the issue to convert to bech32, but we should wait to after the elixir-wallet integration.
I have not found a way yet to convert the 5-bit array [0-31] from bech32 decoding to binary yet

**Comment by thepiwo** [comment]
https://www.youtube.com/watch?v=NqiN9VFE4CU

**Comment by thepiwo** [comment]
closed by https://github.com/aeternity/elixir-research/pull/225
