### ISSUE TITLE
Address types (wallets, contracts, votings...)

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#233]
I would like to propose changes to chain_state to make it possible to treat transactions differently based on the `to_acc` address. This will make it possible to have just one transaction type. When an transaction is executed `to_acc` address controls the flow of execution. 
If `to_acc` address is:
- a contract - function for handling transactions to contracts is executed
- a wallet (normal account) - current function for adding balance is executed
- a special (constant/fixed/predefind) string - a special blockchain operation can be executed. for example: burning tokens, storing data, creation of a contract, creation of a voting...

_This is an completely opposite approach to adding many different transaction types. Instead we add different address types._

**Comment by thepiwo** [comment]
can you explain the advantages further? What is the difference to https://github.com/aeternity/elixir-research/issues/203?

**Comment by cytadela8** [comment]
So this is a different approach by instead of creating different transaction types, we use different object types in `chain_state`. One could have different transaction structure for transactions to contracts, voting, creating contracts, creating voting etc., but there is no need for that. Deciding what to do with a transaction can be done only depending on the `to_acc` address. My reasoning is: _Let's call all of the contracts, votings, accounts and other such structures BlockchainObjects._
- We already have to have different Elixir structures for different types of BlockchainObjects.
- We have to store BlockchainObjects somewhere. We could store more maps like "chain_state", but I consider it simpler to store everything in already existing `chain_state` map.
- When everything is stored in `chain_state` accessing information about different types of BlockchainObjects can be done the same way. There only needs to exist a function that returns the structure of BlockchainObject with a given address. (see #194 implementation, you access both accounts and votings with: Chain.chain_state()[address])
- Different "kinds" of transactions can be handled just by attaching different data to them - votings will expect different fields in the "data" part of transaction, contracts different etc. The advantages of this I can think of are:
    - any interface for creating transactions can make it possible to create any transaction by just leave giving free access to the data field to the user. 
    - we won't need multiple functions for creation different transaction objects, serializing them or any other interaction with them. 
    - this should make it easier for contracts to create different transaction types and (for example) for multi sig wallets to handle all kinds of transactions without understanding their "kinds".
- one problem with this idea is multi signature transactions. This can be handled by changing the current structure of transaction to have a list in `from_acc` and `signature` fields.

**Comment by gspasov** [comment]
In our opinion (@rdimitrovbg  and mine) this approach is deffinatly better than what is used in the master at the moment, but it **still lacks** the _`abstraction that we are trying to achieve`_ in issue #203, because you still use the `case scenario` that we are want to **avoid**.

Yes, we will have diffent types of transactions but we made the logic in such a way, that requires you just to create your new `transaction module/model` and implement the required callbacks to make your `transaction` work on the `blockchain`. No other interventions to the code will be required.

_You will only make your `new transaction module`, implement the required callbacks, and your transaction will be added to the blockchain with no issues._

**Comment by cytadela8** [comment]
@gspasov This would be nice, but I'm not an export in Elixir and I don't know how to do that. Are you aware of some future that allows that? (preferably in secure manner :wink:)

**Comment by thepiwo** [comment]
@gspasov @rdimitrovbg how does this work together with your changes, what should we merge first, does it work together or is it one or the other?

**Comment by gspasov** [comment]
@thepiwo It is one or the other, they are completely different from each other.

**Comment by thepiwo** [comment]
closed by #235
