### ISSUE TITLE
Smart Contracts with AST as "bytecode"

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#237]
# Contracts with AST as code

## Idea

We want smart contracts. We would like to make it possible to create contract functions in Elixir by compiling the Elixir code to AST and using that tree as our "bytecode". Sandboxing of bytecode will be achieved by parsing the AST and searching for illegal calls. 

*To be extended...*

## Plan

- [ ] create the sandbox with serialization and verification of AST tree.
- [ ] make it possible to submit functions to blockchain
- [ ] create contract structure and basic functions
- [ ] connect everything together
- [ ] examples
- [ ] tests

## Possible addictions

- [ ] create utils for easy compilation of Elixir for submission to blockchain

## Time-frame: 22.02.2018 - 09.03.2018

**More desription in #195**

**Comment by thepiwo** [comment]
will close this, as we won't continue prototyping
