### ISSUE TITLE
endpoint to get transactions concerning account from chain

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#92]
- [x] GET `/tx/:account:` endpoint returning all transactions concerning account
tx can be fetched from chainstate, find block, filter transactions
- [x] GET `/tx/:account:?include_proof=true` include merkle proof and block_hash in result, to get the proof fetch the block by hash, build the tx merkle tree, filter the transaction by hash and create the proof via https://github.com/aeternity/gb_merkle_trees/blob/dev/src/gb_merkle_trees.erl#L128

**Comment by thepiwo** [comment]
this needs the transactions added in #91

**Comment by thepiwo** [comment]
@HristianHristov @gspasov whats the state of this task?

**Comment by gspasov** [comment]
The second part of the issue was on hold for us. We wanted to fix the #118 first. Now we'll continue with the second point of this issue.
